model_list:
  - model_name: llama-3.3-70b
    litellm_params:
      model: nvidia_nim/meta/llama-3.3-70b-instruct
      api_key: "{NVIDIA_NIM_API}"

  - model_name: nemetron-3-nano:30b
    litellm_params:
      model: nvidia_nim/nvidia/nemotron-3-nano-30b-a3b
      api_key: "{NVIDIA_NIM_API}"

  - model_name: gpt-oss-20b
    litellm_params:
      model: nvidia_nim/openai/gpt-oss-20b
      api_key: "{NVIDIA_NIM_API}"

  - model_name: gemma-4-31b-it
    litellm_params:
      model: nvidia_nim/google/gemma-4-31b-it
      api_key: "{NVIDIA_NIM_API}"

fallbacks:
  - gpt-oss-20b:
      - gemma-4-31b-it

timeout: 60
